// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 30 Jul 2024 00:35:20 EDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "opus/opus.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

