// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 30 Jul 2024 00:35:20 EDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package opus provides Go bindings for Opus implementation by the Xiph.Org Foundation
*/
package opus
